<!DOCTYPE html SYSTEM "about:legacy-compat">
<html lang="en-US" data-preset="contrast" data-primary-color="#307FFF"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta charset="UTF-8"><meta name="robots" content="noindex"><meta name="built-on" content="2024-11-28T18:28:51.3647269"><title>try-except | Conteúdo do Curso Python para Dynamo do Revit</title><script type="application/json" id="virtual-toc-data">[{"id":"descri-o","level":0,"title":"Descrição","anchor":"#descri-o"},{"id":"sintaxe","level":0,"title":"Sintaxe","anchor":"#sintaxe"},{"id":"capturando-uma-exce-o-espec-fica","level":0,"title":"Capturando uma exceção específica","anchor":"#capturando-uma-exce-o-espec-fica"}]</script><script type="application/json" id="topic-shortcuts"></script><link href="https://resources.jetbrains.com/writerside/apidoc/6.10.0-b518/app.css" rel="stylesheet"><meta name="msapplication-TileColor" content="#000000"><link rel="apple-touch-icon" sizes="180x180" href="https://jetbrains.com/apple-touch-icon.png"><link rel="icon" type="image/png" sizes="32x32" href="https://jetbrains.com/favicon-32x32.png"><link rel="icon" type="image/png" sizes="16x16" href="https://jetbrains.com/favicon-16x16.png"><meta name="msapplication-TileImage" content="https://resources.jetbrains.com/storage/ui/favicons/mstile-144x144.png"><meta name="msapplication-square70x70logo" content="https://resources.jetbrains.com/storage/ui/favicons/mstile-70x70.png"><meta name="msapplication-square150x150logo" content="https://resources.jetbrains.com/storage/ui/favicons/mstile-150x150.png"><meta name="msapplication-wide310x150logo" content="https://resources.jetbrains.com/storage/ui/favicons/mstile-310x150.png"><meta name="msapplication-square310x310logo" content="https://resources.jetbrains.com/storage/ui/favicons/mstile-310x310.png"><meta name="image" content=""><!-- Open Graph --><meta property="og:title" content="try-except | Conteúdo do Curso Python para Dynamo do Revit"><meta property="og:description" content=""><meta property="og:image" content=""><meta property="og:site_name" content="Conteúdo do Curso Python para Dynamo do Revit Help"><meta property="og:type" content="website"><meta property="og:locale" content="en_US"><meta property="og:url" content="writerside-documentation/try-except.html"><!-- End Open Graph --><!-- Twitter Card --><meta name="twitter:card" content="summary_large_image"><meta name="twitter:site" content=""><meta name="twitter:title" content="try-except | Conteúdo do Curso Python para Dynamo do Revit"><meta name="twitter:description" content=""><meta name="twitter:creator" content=""><meta name="twitter:image:src" content=""><!-- End Twitter Card --><!-- Schema.org WebPage --><script type="application/ld+json">{
    "@context": "http://schema.org",
    "@type": "WebPage",
    "@id": "writerside-documentation/try-except.html#webpage",
    "url": "writerside-documentation/try-except.html",
    "name": "try-except | Conteúdo do Curso Python para Dynamo do Revit",
    "description": "",
    "image": "",
    "inLanguage":"en-US"
}</script><!-- End Schema.org --><!-- Schema.org WebSite --><script type="application/ld+json">{
    "@type": "WebSite",
    "@id": "writerside-documentation/#website",
    "url": "writerside-documentation/",
    "name": "Conteúdo do Curso Python para Dynamo do Revit Help"
}</script><!-- End Schema.org --></head><body data-id="try-except" data-main-title="try-except" data-article-props="{&quot;seeAlsoStyle&quot;:&quot;links&quot;}" data-template="article" data-breadcrumbs="Aula-003.md|Aula 003///exceptions.md|Exceções"><div class="wrapper"><main class="panel _main"><header class="panel__header"><div class="container"><h3>Conteúdo do Curso Python para Dynamo do Revit  Help</h3><div class="panel-trigger"></div></div></header><section class="panel__content"><div class="container"><article class="article" data-shortcut-switcher="inactive"><h1 data-toc="try-except" id="try-except.md">try-except</h1><section class="chapter"><h2 id="descri-o" data-toc="descri-o">Descri&ccedil;&atilde;o</h2><p id="qektjz_6">Em Python, podemos lidar com exce&ccedil;&otilde;es usando blocos <code class="code" id="qektjz_10">try</code> e <code class="code" id="qektjz_11">except</code>.</p><p id="qektjz_7">Esses blocos permitem que voc&ecirc; lide com erros de uma maneira controlada, separando o c&oacute;digo de tratamento de erros do c&oacute;digo principal.</p><section class="chapter"><h3 id="vantagens" data-toc="vantagens">Vantagens:</h3><ol class="list _decimal" id="qektjz_12" type="1"><li class="list__item" id="qektjz_13"><p id="qektjz_16"><span class="control" id="qektjz_17">Clareza e Manuten&ccedil;&atilde;o</span>: as exce&ccedil;&otilde;es permitem que o fluxo de controle do programa permane&ccedil;a claro, com o c&oacute;digo principal focado na execu&ccedil;&atilde;o normal e o tratamento de erros localizado em blocos espec&iacute;ficos.</p></li><li class="list__item" id="qektjz_14"><p id="qektjz_18"><span class="control" id="qektjz_19">Tratamento Localizado</span>: as exce&ccedil;&otilde;es permitem o tratamento de erros em n&iacute;veis superiores da pilha de chamadas, em vez de exigir a verifica&ccedil;&atilde;o de erros em cada ponto onde algo pode dar errado.</p></li><li class="list__item" id="qektjz_15"><p id="qektjz_20"><span class="control" id="qektjz_21">Recupera&ccedil;&atilde;o de Erros</span>: elas oferecem uma maneira estruturada de lidar com falhas permitindo que o programa tente uma recupera&ccedil;&atilde;o ou t&eacute;rmino gracioso.</p></li></ol></section><section class="chapter"><h3 id="desvantagens" data-toc="desvantagens">Desvantagens:</h3><ol class="list _decimal" id="qektjz_22" type="1"><li class="list__item" id="qektjz_23"><p id="qektjz_26"><span class="control" id="qektjz_27">Desempenho</span>: o uso de exce&ccedil;&otilde;es pode ter um impacto no desempenho, especialmente em se&ccedil;&otilde;es de c&oacute;digo executadas com frequ&ecirc;ncia, devido ao custo de lan&ccedil;ar e capturar exce&ccedil;&otilde;es.</p></li><li class="list__item" id="qektjz_24"><p id="qektjz_28"><span class="control" id="qektjz_29">Complexidade</span>: a introdu&ccedil;&atilde;o de muitas exce&ccedil;&otilde;es pode tornar o c&oacute;digo mais dif&iacute;cil de entender e manter, especialmente em sistemas complexos.</p></li><li class="list__item" id="qektjz_25"><p id="qektjz_30"><span class="control" id="qektjz_31">Oculta&ccedil;&atilde;o de Erros</span>: se usadas indevidamente, exce&ccedil;&otilde;es podem ocultar erros, dificultando diagnosticar problemas reais no c&oacute;digo.</p></li></ol></section></section><section class="chapter"><h2 id="sintaxe" data-toc="sintaxe">Sintaxe</h2><div class="code-block" data-lang="python">
try:
    resultado = 10 / 0
except ZeroDivisionError:
    resultado = None
    
print(&quot;Erro: Divisão por zero não é permitida.&quot;)
</div><p id="qektjz_33">O bloco try tenta executar o c&oacute;digo problem&aacute;tico, enquanto o bloco except trata a exce&ccedil;&atilde;o espec&iacute;fica do erro <code class="code" id="qektjz_34">ZeroDivisionError</code>.</p></section><section class="chapter"><h2 id="capturando-uma-exce-o-espec-fica" data-toc="capturando-uma-exce-o-espec-fica">Capturando uma exce&ccedil;&atilde;o espec&iacute;fica</h2><p id="qektjz_35">Para capturar uma exce&ccedil;&atilde;o espec&iacute;fica, voc&ecirc; pode usar a sintaxe <code class="code" id="qektjz_38">except</code> seguida pelo nome da exce&ccedil;&atilde;o.</p><div class="code-block" data-lang="python">
try:
    # Código problemático
except NomeDaExcecao:
    # Tratamento da exceção
</div><section class="chapter"><h3 id="exemplo" data-toc="exemplo">Exemplo</h3><p id="qektjz_39">Podemos criar um bloco de c&oacute;digo que seja executado caso uma exce&ccedil;&atilde;o espec&iacute;fica ocorra.</p><p id="qektjz_40">Veja um exemplo abaixo de como fazer isso:</p><div class="code-block" data-lang="python">
def calcular_media_lista(valores):
    try:
        numeros = [int(valor) for valor in valores]
        media = sum(numeros) / len(numeros)
        print(f&quot;A média dos números é: {media}&quot;)

    except ValueError as e:
        print(
            f&quot;Erro: A lista contém dados não numéricos. Detalhes: {e}&quot;
        )
    except ZeroDivisionError:
        print(
            &quot;Erro: Não é possível calcular &quot; + 
            &quot;a média de uma lista vazia.&quot;
        )
    except Exception as e:
        print(f&quot;Ocorreu um erro inesperado: {e}&quot;)

# Testando com uma lista contendo valores inválidos
valores = [&quot;10&quot;, &quot;20&quot;, &quot;abc&quot;, &quot;30&quot;]
calcular_media_lista(valores)

# Testando com uma lista vazia
valores = []
calcular_media_lista(valores)
</div></section></section><div class="last-modified">Last modified: 28 November 2024</div><div data-feedback-placeholder="true"></div><div class="navigation-links _bottom"><a href="exceptions.html" class="navigation-links__prev">Exce&ccedil;&otilde;es</a><a href="raise-an-exception.html" class="navigation-links__next">Lan&ccedil;ando uma exce&ccedil;&atilde;o</a></div></article><div id="disqus_thread"></div></div></section></main></div><script src="https://resources.jetbrains.com/writerside/apidoc/6.10.0-b518/app.js"></script></body></html>